[project]
name = "seegfellow-dev"
version = "0.0.0"
requires-python = ">=3.9"
dependencies = [
    "nibabel",
]

[dependency-groups]
dev = [
    "pytest",
    "scipy>=1.13.1",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.pyright]
venvPath = "."
venv = ".venv"
