[project]
name = "seegfellow-dev"
version = "0.0.0"
requires-python = ">=3.9"
dependencies = [
    "deepbet",
    "nibabel",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.pyright]
venvPath = "."
venv = ".venv"
